### ISSUE TITLE
Why does it not restart snark worker properly?

### ISSUE THREAD

**Issue by vanphandinh** [c29r3/mina-snark-stopper#4]
![Screen Shot 2021-01-10 at 11 48 15 AM](https://user-images.githubusercontent.com/13887599/104114695-d6fbce80-5339-11eb-853d-259fa393b4c1.png)

My node was producing block and then the script restarted the snark worker again but it seems it didn't work. Then I've tried to restart the script docker several times

**Comment by c29r3** [comment]
It seems that in the new release, the developers made changes to GRAPHQL and for this reason the stopper does not work. I'll see what has changed tonight

**Comment by vanphandinh** [comment]
> It seems that in the new release, the developers made changes to GRAPHQL and for this reason the stopper does not work. I'll see what has changed tonight
> 
> Please post a screenshot of `coda client status`

Great. Looking forward to see your new release.

**Comment by vanphandinh** [comment]
> Please post a screenshot of `coda client status`

I just started SNARK worker by myself, do I need to screenshot it?

**Comment by vanphandinh** [comment]
![Screen Shot 2021-01-10 at 10 26 34 PM](https://user-images.githubusercontent.com/13887599/104127116-e65b3600-5392-11eb-90a5-443498fe2e85.png)

**Comment by c29r3** [comment]
Hmm, now I checked - stopper works fine for me
`Git SHA-1: [DIRTY]b14e32415b15af04865ca069af31cea7716be251`
![image](https://user-images.githubusercontent.com/52304443/104130708-52ce3900-5383-11eb-88b3-5f018c53507f.png)  


Can you try this?
```bash
docker rm -f snark-stopper; \
docker system prune -af; \
docker run -d \
--volume $(pwd)/config.yml:/mina/config.yml \
--net=host \
--restart always \
--name snark-stopper \
c29r3/snark-stopper; \
docker logs -f snark-stopper
```

**Comment by vanphandinh** [comment]
> Hmm, now I checked - stopper works fine for me
> `Git SHA-1: [DIRTY]b14e32415b15af04865ca069af31cea7716be251`
> ![image](https://user-images.githubusercontent.com/52304443/104130708-52ce3900-5383-11eb-88b3-5f018c53507f.png)
> 
> Can you try this?
> 
> ```shell
> docker rm -f snark-stopper; \
> docker system prune -af; \
> docker run -d \
> --volume $(pwd)/config.yml:/mina/config.yml \
> --net=host \
> --restart always \
> --name snark-stopper \
> c29r3/snark-stopper; \
> docker logs -f snark-stopper
> ```

Here are my logs
![Screen Shot 2021-01-11 at 9 42 22 AM](https://user-images.githubusercontent.com/13887599/104143276-63b59380-53f1-11eb-8994-45e4951cf8aa.png)

**Comment by vanphandinh** [comment]
This is my: coda client status
![Screen Shot 2021-01-11 at 9 44 06 AM](https://user-images.githubusercontent.com/13887599/104143386-c73fc100-53f1-11eb-86bd-abdd5c6f7df5.png)

**Comment by c29r3** [comment]
Now it is clear.
The script tries to get the time after which the next block will be produced, but in this epoch your validator did not get the right to produce the block and None is returned instead of StartTime.
In general, this is not a problem. The script checks the next production time block every 2 minutes. That is, in the next era the script will work as it should.

![image](https://user-images.githubusercontent.com/52304443/104143617-483a9080-53d1-11eb-93df-4b11a672924d.png)

Can you please post output from this command? 
```bash
curl -s http://localhost:3085/graphql?query=query%20MyQuery%20%7B%0A%20%20version%0A%20%20daemonStatus%20%7B%0A%20%20%20%20nextBlockProduction%20%7B%0A%20%20%20%20%20%20times%20%7B%0A%20%20%20%20%20%20%20%20endTime%0A%20%20%20%20%20%20%20%20epoch%0A%20%20%20%20%20%20%20%20globalSlot%0A%20%20%20%20%20%20%20%20slot%0A%20%20%20%20%20%20%20%20startTime%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A | jq .
```

**Comment by vanphandinh** [comment]
> Now it is clear.
> The script tries to get the time after which the next block will be produced, but in this epoch your validator did not get the right to produce the block and None is returned instead of StartTime.
> In general, this is not a problem. The script checks the next production time block every 2 minutes. That is, in the next era the script will work as it should.
> 
> ![image](https://user-images.githubusercontent.com/52304443/104143617-483a9080-53d1-11eb-93df-4b11a672924d.png)
> 
> Can you please post output from this command? I need this to understand how to better handle these kinds of errors
> 
> ```shell
> curl -s http://localhost:3085/graphql?query=query%20MyQuery%20%7B%0A%20%20version%0A%20%20daemonStatus%20%7B%0A%20%20%20%20nextBlockProduction%20%7B%0A%20%20%20%20%20%20times%20%7B%0A%20%20%20%20%20%20%20%20endTime%0A%20%20%20%20%20%20%20%20epoch%0A%20%20%20%20%20%20%20%20globalSlot%0A%20%20%20%20%20%20%20%20slot%0A%20%20%20%20%20%20%20%20startTime%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A | jq .
> ```

![Screen Shot 2021-01-11 at 11 49 59 AM](https://user-images.githubusercontent.com/13887599/104148033-2bb74c00-5403-11eb-86e4-bcf394dff9a1.png)

**Comment by vanphandinh** [comment]
It seems did not set snark-fee and snark-worker

**Comment by vanphandinh** [comment]
@c29r3 Bro, the latest version still doesn't set snark-fee and snark-worker

![Screen Shot 2021-01-12 at 10 06 49 AM](https://user-images.githubusercontent.com/13887599/104264393-210dbd00-54be-11eb-8606-dd49a145a1aa.png)
![Screen Shot 2021-01-12 at 10 07 54 AM](https://user-images.githubusercontent.com/13887599/104264401-23701700-54be-11eb-9dd5-e3802f9aa5c6.png)

**Comment by c29r3** [comment]
> @c29r3 Bro, the latest version still doesn't set snark-fee and snark-worker. The snark worker does work
> 
> ![Screen Shot 2021-01-12 at 10 06 49 AM](https://user-images.githubusercontent.com/13887599/104264393-210dbd00-54be-11eb-8606-dd49a145a1aa.png)
> ![Screen Shot 2021-01-12 at 10 07 54 AM](https://user-images.githubusercontent.com/13887599/104264401-23701700-54be-11eb-9dd5-e3802f9aa5c6.png)

Must be fixed now 🙂  
You need to update config file and docker image  
```bash
docker rm -f snark-stopper; \
curl -s https://raw.githubusercontent.com/c29r3/mina-snark-stopper/master/config.yml > config.yml; \
docker pull c29r3/snark-stopper
```

**Comment by vanphandinh** [comment]
Great, when I try to run this script when the coda node is bootstrapping, will it be run automatically after my node is synced?
